---
title: "AboutUs"
author: "Tamás Baráth"
date: "20/02/2020"
output: html_document
runtime: shiny
---

## Team Bae's
### About our team

We are a team of statistics and engineering students here at KU Leuven. The team consists of: Tamás Baráth, Harold Heymans, Jente Snoeck, Björn Van der Auwera and Paul van Tieghem.



### About the tool
In Belgium:
- In 2018 there were approximately 24000 traffic accidents with wounded or dead people
- 4 out of 10 casualties are pedestrians or people riding a bike
- 92% of deadly accidents happen outside of highways
- Currently allocation of mobile speed traps is done on an ad-hoc basis

We created a proof of concept for a police tool based on the Telraam data project in Leuven, which can be found
on the following [website](https://www.telraam.net). The tool can be used to identify areas where
police can optimise revenue and/or traffic risk reduction by deploying mobile speed-checking units. 
The indentification is done by setting location and time restricitons and by specifing a trade-off between risk and income. 

The user can select the desired month, day and hours for deploying speed cameras, the desired ratio of income maximisation/risk minimasation, the number of units available and the province of interest in Belgium. The tool will suggest the best locations for the available units in tabular form as well as on a map.

We accept donations in the form of one of travel vouchers. ;\^)
